Document: audio-recorder
Title: Debian audio-recorder Manual
Author: <insert document author here>
Abstract: This manual describes what audio-recorder is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/audio-recorder/audio-recorder.sgml.gz

Format: postscript
Files: /usr/share/doc/audio-recorder/audio-recorder.ps.gz

Format: text
Files: /usr/share/doc/audio-recorder/audio-recorder.text.gz

Format: HTML
Index: /usr/share/doc/audio-recorder/html/index.html
Files: /usr/share/doc/audio-recorder/html/*.html
